name: Keep Repo Active

on:
  workflow_dispatch:
  schedule:
    # 매일 자정에 실행 (한국 시간 기준)
    - cron: '15 15 * * *'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update README
        run: |
          # 새로운 업데이트 라인을 변수에 저장합니다.
          NEW_LINE="Last updated on $(TZ='Asia/Seoul' date '+%Y-%m-%d %H:%M:%S %Z')"
          
          # README.md에서 기존 'Last updated on'으로 시작하는 라인을 제외한 내용만 임시 파일에 저장합니다.
          grep -v "^Last updated on" README.md > temp_readme.md
          
          # 임시 파일의 맨 위에 새로운 업데이트 라인을 추가하여 최종 README.md 파일을 덮어씁니다.
          { echo "$NEW_LINE"; cat temp_readme.md; } > README.md

          # Git 설정 및 푸시 (이 부분은 이전과 동일합니다)
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add README.md
          git diff --quiet && git diff --staged --quiet || git commit -m "Update README to keep repo active"
          git push
